"""Compatibility exports for config data models."""

from __future__ import annotations

from .models import (
    ApplicationSettings,
    BasicConfig,
    BasicSettings,
    ContentHandlersConfig,
    ContentHandlerSettings,
    FeedFetchSettings,
    GlobalConfig,
    HttpConfig,
    HttpSettings,
    MediaConfig,
    MediaPlatformLimits,
    MediaSettings,
    PlatformSenderStrategyConfig,
    PlatformStrategySettings,
    RouteKnowledgeConfig,
    RouteKnowledgeSettings,
    RsshubPluginConfig,
    RSSSettings,
    SchedulerSettings,
    SenderStrategiesConfig,
    SenderStrategySettings,
    SubscriptionDefaults,
)

__all__ = [
    "ApplicationSettings",
    "BasicConfig",
    "BasicSettings",
    "ContentHandlersConfig",
    "ContentHandlerSettings",
    "FeedFetchSettings",
    "GlobalConfig",
    "HttpConfig",
    "HttpSettings",
    "MediaConfig",
    "MediaSettings",
    "MediaPlatformLimits",
    "PlatformSenderStrategyConfig",
    "PlatformStrategySettings",
    "RouteKnowledgeConfig",
    "RouteKnowledgeSettings",
    "RsshubPluginConfig",
    "RSSSettings",
    "SchedulerSettings",
    "SenderStrategiesConfig",
    "SenderStrategySettings",
    "SubscriptionDefaults",
]
