"""Subscription import/export helpers for RSSHub plugin."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import UTC, datetime

import tomllib

EXPORT_FORMAT = "astrbot-rsshub-subscriptions"
EXPORT_VERSION = 1

# Fields to exclude from export (these are context-specific and should be calculated at runtime)
# - ID fields should be generated by the current bot instance
# - target_session is calculated based on current session context
EXPORT_EXCLUDED_FIELDS = {"id", "sid", "sub_id", "target_session"}

STRING_FIELDS = {
    "title",
    "tags",
    "target_session",
    "platform_name",
    "feed_title",
}

INT_FIELDS = {
    "notify",
    "send_mode",
    "length_limit",
    "link_preview",
    "display_author",
    "display_via",
    "display_title",
    "display_entry_tags",
    "style",
    "display_media",
    "interval",
}


@dataclass(slots=True)
class ImportSubscriptionRecord:
    link: str
    feed_title: str | None = None
    options: dict[str, int | str] = field(default_factory=dict)


@dataclass(slots=True)
class SubscriptionImportPayload:
    records: list[ImportSubscriptionRecord] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def serialize_subscriptions_to_toml(*, user_id: str, subscriptions: list) -> str:
    """Serialize user subscriptions to TOML text."""
    lines = [
        f"format = {_toml_string(EXPORT_FORMAT)}",
        f"version = {EXPORT_VERSION}",
        f"exported_at = {_toml_string(datetime.now(UTC).isoformat())}",
        f"user_id = {_toml_string(str(user_id))}",
        "",
    ]

    for sub in subscriptions:
        feed = getattr(sub, "feed", None)
        if feed is None:
            continue

        lines.append("[[subscriptions]]")
        lines.append(f"link = {_toml_string(str(feed.link))}")
        if feed.title:
            lines.append(f"feed_title = {_toml_string(str(feed.title))}")

        for key in sorted(STRING_FIELDS - {"feed_title"}):
            # Skip fields that should be calculated at runtime
            if key in EXPORT_EXCLUDED_FIELDS:
                continue
            value = getattr(sub, key, None)
            if isinstance(value, str) and value.strip():
                lines.append(f"{key} = {_toml_string(value)}")

        for key in sorted(INT_FIELDS):
            # Skip fields that should be calculated at runtime
            if key in EXPORT_EXCLUDED_FIELDS:
                continue
            value = getattr(sub, key, None)
            if isinstance(value, bool):
                continue
            if isinstance(value, int):
                lines.append(f"{key} = {value}")

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _parse_int_value(raw, *, key: str, index: int) -> tuple[int | None, str | None]:
    if isinstance(raw, bool):
        return None, f"subscriptions[{index}].{key} must be an integer"

    if isinstance(raw, int):
        return raw, None

    if isinstance(raw, str):
        stripped = raw.strip()
        if not stripped:
            return None, f"subscriptions[{index}].{key} cannot be empty"
        if not re.fullmatch(r"[+-]?\d+", stripped):
            return None, f"subscriptions[{index}].{key} must be an integer"
        return int(stripped), None

    return None, f"subscriptions[{index}].{key} must be an integer"


def parse_subscriptions_toml(content: str) -> SubscriptionImportPayload:
    """Parse and validate subscription import TOML content."""
    payload = SubscriptionImportPayload()

    try:
        data = tomllib.loads(content)
    except tomllib.TOMLDecodeError as ex:
        payload.errors.append(f"TOML parse failed: {ex}")
        return payload

    if not isinstance(data, dict):
        payload.errors.append("TOML root must be a table")
        return payload

    format_name = data.get("format")
    if format_name and format_name != EXPORT_FORMAT:
        payload.warnings.append(
            f"Unexpected format={format_name!r}; parser will try best-effort import"
        )

    version = data.get("version")
    if version is not None and version != EXPORT_VERSION:
        payload.warnings.append(
            f"Unexpected version={version!r}; parser will try best-effort import"
        )

    subs = data.get("subscriptions")
    if not isinstance(subs, list):
        payload.errors.append("Missing or invalid subscriptions array")
        return payload

    for i, raw in enumerate(subs, start=1):
        if not isinstance(raw, dict):
            payload.errors.append(f"subscriptions[{i}] must be a table")
            continue

        link = str(raw.get("link") or "").strip()
        if not link:
            payload.errors.append(f"subscriptions[{i}].link is required")
            continue
        if not re.match(r"^https?://", link, re.IGNORECASE):
            payload.errors.append(
                f"subscriptions[{i}].link must start with http:// or https://"
            )
            continue

        record = ImportSubscriptionRecord(link=link)

        # Warn if ID fields are present in the import file (they will be ignored)
        ID_FIELDS = {"id", "sid", "sub_id"}
        for id_field in ID_FIELDS:
            if id_field in raw:
                payload.warnings.append(
                    f"subscriptions[{i}].{id_field} is present but will be ignored; "
                    f"new ID will be generated by the current bot instance"
                )

        feed_title = raw.get("feed_title")
        if feed_title is not None:
            if not isinstance(feed_title, str):
                payload.errors.append(f"subscriptions[{i}].feed_title must be a string")
                continue
            title = feed_title.strip()
            if title:
                record.feed_title = title

        has_error = False
        for key in STRING_FIELDS - {"feed_title"}:
            if key not in raw:
                continue
            value = raw.get(key)
            if value is None:
                continue
            if not isinstance(value, str):
                payload.errors.append(f"subscriptions[{i}].{key} must be a string")
                has_error = True
                continue
            normalized = value.strip()
            if normalized:
                record.options[key] = normalized

        for key in INT_FIELDS:
            if key not in raw:
                continue
            parsed, error = _parse_int_value(raw.get(key), key=key, index=i)
            if error:
                payload.errors.append(error)
                has_error = True
                continue
            if parsed is not None:
                record.options[key] = parsed

        if has_error:
            continue

        payload.records.append(record)

    return payload
